# Generated by Django 3.2 on 2021-09-02 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('inventory', '0001_initial'),
        ('delivery', '0001_initial'),
        ('products', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepointdelivery',
            name='sale_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.salepoint'),
        ),
        migrations.AddField(
            model_name='outproduct',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='outproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='outdelivery',
            name='products',
            field=models.ManyToManyField(null=True, to='delivery.OutProduct'),
        ),
        migrations.AddField(
            model_name='outdelivery',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
