# Generated by Django 3.2 on 2021-09-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_outdelivery_representitive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outproduct',
            name='product',
        ),
    ]
