# Generated by Django 3.2 on 2021-09-06 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20210905_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepointinvoice',
            name='out_delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.outdelivery'),
            preserve_default=False,
        ),
    ]
