# Generated by Django 3.2 on 2021-09-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_items_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='items_left',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
